### ISSUE TITLE
UI Improvement needed

### ISSUE THREAD

**Issue by viveeeeeek** [viveeeeeek/flutter-bmi-calculator#2]
You can improve app UI.
Add features

**Comment by Manavpreeet** [comment]
Hi vivek, I would like to work on this

**Comment by viveeeeeek** [comment]
Sure @Manavpreeet I'll assign this issue to you.

**Comment by Dhruvil-P** [comment]
Hey @viveeeeeek, Can I work on this issue too?

**Comment by viveeeeeek** [comment]
sure @Dhruvil-P
