### ISSUE TITLE
Add app screenshots 

### ISSUE THREAD

**Issue by viveeeeeek** [viveeeeeek/flutter-bmi-calculator#7]
Add app screenshots (for both Mobile & Web) with mockup devices or something similar to that.
You can also add app demo video also if you like.

**Comment by Giancarmine** [comment]
Please assign me this issue!

**Comment by viveeeeeek** [comment]
sure

**Comment by Giancarmine** [comment]
Find the PR [here](https://github.com/viveeeeeek/flutter-bmi-calculator/pull/8)

**Comment by viveeeeeek** [comment]
Nice 👍🏼
